
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER']||= "jim" %>
  password: <%= ENV['POSTGRES_PASSWORD']||= "jim" %>
  host: <%= ENV['POSTGRES_HOST']||= localhost %>
  # username: "jim"
  # password: "jim"
  # host: localhost


development:
  <<: *default
  database: module1_development

 
test:
  <<: *default
  database: module1_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>


